// Generated by research/scripts/export_vowel_presets.py.
// Research output: listening-test before replacing production vowel defaults.
// Source: research/data/processed/analysis/utau-vowel-formants.csv

export type GeneratedVowelId = "a" | "i" | "u" | "e" | "o";

export type GeneratedFormant = {
  frequency: number;
  bandwidth: number;
  gain: number;
};

export type GeneratedVowelProfile = {
  id: GeneratedVowelId;
  label: string;
  formants: [GeneratedFormant, GeneratedFormant, GeneratedFormant];
};

export const GENERATED_UTAU_VOWEL_PROFILES: Record<GeneratedVowelId, GeneratedVowelProfile> = {
  a: {
    id: "a",
    label: "/a/",
    formants: [
      { frequency: 962, bandwidth: 123, gain: 0.462 },
      { frequency: 1405, bandwidth: 74, gain: 1.000 },
      { frequency: 2378, bandwidth: 102, gain: 0.229 },
    ],
  },
  i: {
    id: "i",
    label: "/i/",
    formants: [
      { frequency: 376, bandwidth: 52, gain: 0.309 },
      { frequency: 2831, bandwidth: 195, gain: 0.278 },
      { frequency: 3725, bandwidth: 85, gain: 0.959 },
    ],
  },
  u: {
    id: "u",
    label: "/u/",
    formants: [
      { frequency: 498, bandwidth: 80, gain: 0.499 },
      { frequency: 1326, bandwidth: 98, gain: 0.448 },
      { frequency: 1762, bandwidth: 75, gain: 0.997 },
    ],
  },
  e: {
    id: "e",
    label: "/e/",
    formants: [
      { frequency: 665, bandwidth: 60, gain: 0.501 },
      { frequency: 2354, bandwidth: 128, gain: 0.120 },
      { frequency: 3270, bandwidth: 128, gain: 0.293 },
    ],
  },
  o: {
    id: "o",
    label: "/o/",
    formants: [
      { frequency: 717, bandwidth: 67, gain: 0.178 },
      { frequency: 1048, bandwidth: 68, gain: 1.000 },
      { frequency: 3171, bandwidth: 229, gain: 0.120 },
    ],
  },
};

export const GENERATED_UTAU_VOWEL_ORDER: GeneratedVowelId[] = ["a", "i", "u", "e", "o"];
